# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Syllabus"
  url = "syllabus/"
  weight = 10
  
[[main]]
  name = "Calendar"
  url = "calendar/2019-2020.html"
  weight = 15  
#[[main]]
#  name = "Course"
#  url = "course/"
#  weight = 15

[[main]]
  name = "Posts"
  url = "post/"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Papers"
  url = "publication/"
  weight = 30

#[[main]]
#  name = "Tutorials"
#  url = "tutorials/"
#  weight = 50

[[main]]
  name = "Talks"
  url = "talk/"
  weight = 50

[[main]]
  name = "Handbook"
  url = "handbook/"
  weight = 55
  
[[main]]
  name = "Submissions"
  url = "submissions/"
  weight = 55
  
[[main]]
  name = "Office Hours"
  url = "#officehours"
  weight = 60
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
